name: CI run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: update packages
      run: sudo apt update

    # set up scala
    - name: install scala
      run: sudo apt install scala

    # set up ocaml
    - name : install ocaml 
      run: sudo apt install ocaml

    # set up java
    - name : install java 
      run: sudo apt install default-jdk  

    # set up haskell
    - name : install haskell 
      run: sudo apt install haskell-platform

    # set up .swi-prolog
    - name : install .swi-prolog 
      run: sudo apt install swi-prolog

    # set up kotlin
    - name : install kotlin 
      run: sudo snap install --classic kotlin

    # set up J
    - name : install J
      run : |
        curl https://www.jsoftware.com/download/j901/install/j901_amd64.deb > j901_amd64.deb
        sudo apt install ./j901_amd64.deb

    # set up ChezScheme
    - name : install ChezScheme
      run : sudo apt install chezscheme

    # Runs the main script script
    - name: Run script
      run: ./run.sh